# Dockerfile.api (API Node/Express)
FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY . .

ENV NODE_ENV=production
ENV PORT=${PORT}

EXPOSE 3000
CMD ["node", "server.js"]
